#!/usr/bin/env python3
"""
verify.py - executing stop condition for the patch loop.

Reproduces a PoC on the unpatched fixture, applies the candidate patch, confirms
the PoC no longer reproduces, and confirms tests still pass. Evidence is
generated by execution; the agent cannot assert a result it did not produce.

Usage:
    python3 verify.py PATCH_FILE

Exit code:
    0  patch verified - loop may close
    1  blocking finding - keep iterating
    2  usage or setup error

Dependencies: Python 3.8+, git on PATH for patch application.
"""

import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

LOOP_DIR = Path(__file__).resolve().parent
FIXTURE = LOOP_DIR / "fixture"
CONFIG = FIXTURE / "loop.config.json"


class Finding:
    def __init__(self, code, message):
        self.code = code
        self.message = message


def load_config():
    try:
        with open(CONFIG, encoding="utf-8") as handle:
            data = json.load(handle)
    except (OSError, json.JSONDecodeError) as error:
        print(f"error: invalid loop.config.json: {error}", file=sys.stderr)
        sys.exit(2)
    for key in ("poc", "tests"):
        if key not in data or not isinstance(data[key], list) or not data[key]:
            print(f"error: loop.config.json missing command list: {key}", file=sys.stderr)
            sys.exit(2)
    return data


def run_commands(cwd, commands):
    return subprocess.run(commands, cwd=cwd, check=False)


def apply_patch(workdir, patch_path):
    git = shutil.which("git")
    if git:
        init = subprocess.run([git, "init", "-q"], cwd=workdir, check=False)
        if init.returncode != 0:
            return False, "git init failed"
        add = subprocess.run([git, "add", "-A"], cwd=workdir, check=False)
        if add.returncode != 0:
            return False, "git add failed"
        apply = subprocess.run(
            [git, "apply", "--whitespace=nowarn", str(patch_path)],
            cwd=workdir,
            check=False,
            capture_output=True,
            text=True,
        )
        if apply.returncode == 0:
            return True, None
        patch_bin = shutil.which("patch")
        if patch_bin:
            fallback = subprocess.run(
                [patch_bin, "-p1", "-i", str(patch_path)],
                cwd=workdir,
                check=False,
                capture_output=True,
                text=True,
            )
            if fallback.returncode == 0:
                return True, None
            return False, fallback.stderr.strip() or fallback.stdout.strip() or "patch command failed"
        detail = apply.stderr.strip() or apply.stdout.strip() or "git apply failed"
        return False, detail
    patch_bin = shutil.which("patch")
    if patch_bin:
        apply = subprocess.run(
            [patch_bin, "-p1", "-i", str(patch_path)],
            cwd=workdir,
            check=False,
            capture_output=True,
            text=True,
        )
        if apply.returncode == 0:
            return True, None
        return False, apply.stderr.strip() or "patch command failed"
    return False, "neither git nor patch found on PATH"


def verify_patch(patch_path):
    config = load_config()
    findings = []

    with tempfile.TemporaryDirectory(prefix="loopforge-patch-") as tmp:
        workdir = Path(tmp)
        shutil.copytree(FIXTURE, workdir, dirs_exist_ok=True)
        marker = workdir / ".poc_marker"
        marker.unlink(missing_ok=True)

        poc_before = run_commands(workdir, config["poc"])
        if poc_before.returncode != 0:
            findings.append(Finding("PT-POC-BEFORE", "PoC did not reproduce on vulnerable baseline"))

        ok, err = apply_patch(workdir, patch_path)
        if not ok:
            findings.append(Finding("PT-APPLY-FAIL", f"patch did not apply cleanly: {err}"))

        poc_after = run_commands(workdir, config["poc"])
        tests_after = run_commands(workdir, config["tests"])

        if poc_after.returncode == 0:
            findings.append(Finding("PT-NO-FIX", "PoC still reproduces after patch"))
        if tests_after.returncode != 0:
            findings.append(Finding("PT-BREAKS-TESTS", "tests fail after patch"))

        evidence = (
            f"poc_before_exit={poc_before.returncode} "
            f"poc_after_exit={poc_after.returncode} "
            f"tests_after_exit={tests_after.returncode}"
        )

    return findings, evidence


def main():
    if len(sys.argv) != 2:
        print("usage: python3 verify.py PATCH_FILE", file=sys.stderr)
        sys.exit(2)

    patch_path = Path(sys.argv[1])
    if not patch_path.is_file():
        print(f"error: patch file not found: {patch_path}", file=sys.stderr)
        sys.exit(2)

    findings, evidence = verify_patch(patch_path.resolve())
    print(f"\npatch verify  ::  {patch_path.name}")
    print(f"  evidence: {evidence}")
    print("")
    if findings:
        for finding in findings:
            print(f"  BLOCK  {finding.code:16} {finding.message}")
        print("")
        print("  RESULT: BLOCKED -- loop stays open")
        print("")
        sys.exit(1)

    print("  RESULT: PASS -- loop may close")
    print("")
    sys.exit(0)


if __name__ == "__main__":
    main()
